spring:
  application:
    name: 'hub-gateway'
  cloud:
    config:
      auto-refresh: true
      refresh-interval: 60
    gateway:
      routes:
      - id: greet
        uri: lb://poc-service
        predicates:
        - Path=/greeting
      - id: httpbin
        uri: http://httpbin.org:80
        predicates:
        - Path=/httpbin
      - id: practitioner
        uri: lb://poc-service
        predicates:
        - Path=/practitioner/**

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
          - refresh

---
# shall include: "*" in non production only
spring:
  config:
    activate:
      on-profile: test
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
---