spring:
  cloud:
    config:
      auto-refresh: true
      refresh-interval: 60
    gateway:
      routes:
        - id: httpbin
          uri: http://httpbin.org:80
          predicates:
          - Path=/get
        - id: randomuser-test
          uri: https://poc-app-poc-app-service.azuremicroservices.io
          predicates:
          - Path=/randomuser
        - id: vault-access-test
          uri: https://poc-app-poc-app-service.azuremicroservices.io
          predicates:
          - Path=/vault
        - id: config-access-test
          uri: https://primary:HEBLBWsxGLNHFRX6zcaiu8vMmx6ohIpAxGlg1gB7VjITHquxPYleScoyQu01HCmT@poc-app.test.private.azuremicroservices.io/poc-app-service/default
          predicates:
          - Path=/testproperty

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: refresh

---

spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: info
    org.springframework.web: error
    org.springframework.security: info
    org.springframework.cloud.netflix: error
    com.netflix.discovery: error
    org.springframework.cloud.endpoint: error

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---