spring:
  cloud:
    config:
      auto-refresh: true
      refresh-interval: 60
    gateway:
      routes:
        - id: httpbin
          uri: http://httpbin.org:80
          predicates:
          - Path=/get
        - id: randomuser-test
          uri: https://20.250.209.139
          predicates:
          - Path=/randomuser
        - id: vault-access-test
          uri: https://20.250.209.139
          predicates:
          - Path=/vault
        - id: config-access-test
          uri: https://20.250.209.139
          predicates:
          - Path=/testproperty

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: refresh

---

spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: info
    org.springframework.cloud.netflix: error
    com.netflix.discovery: error
    org.nahsi.example.test.scheduler: debug

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---