spring:
  cloud:
    config:
      auto-refresh: true
      refresh-interval: 60
    gateway:
      routes:
        - id: httpbin
          uri: http://httpbin.org:80
          predicates:
          - Path=/get
        - id: random
          uri: http://randomuser.me
          predicates:
          - Path=/api

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
          - refresh
          - gateway

