spring:
  cloud:
    config:
      auto-refresh: true
      refresh-interval: 60
    gateway:
      routes:
      - id: httpbin
        uri: http://httpbin.org:80
        predicates:
        - Path=/httpbin

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
          - refresh

