spring:
  application:
    name: hub-gateway
  cloud:
    gateway:
      routes:
        - id: httpbin
          uri: http://httpbin.org:80
          predicates:
          - Path=/get
        - id: random
          uri: http://randomuser.me/
          predicates:
          - Path=/api

    config:
      auto-refresh: true
      refresh-interval: 60

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
          - refresh

