spring:
  cloud:
    config:
      auto-refresh: true
      refresh-interval: 60
    gateway:
      routes:
      - id: httpbin
        uri: http://httpbin.org:80
        predicates:
        - Path=/httpbin
      - id: baeldung_route
        uri: http://baeldung.com
        predicates:
        - Path=/baeldung/

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
          - refresh

---
# shall include: "*" in non production only
spring:
  config:
    activate:
      on-profile: test
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
---