
testProperty: test property setting

spring:
    cloud:
         config:
          auto-refresh: true
          refresh-interval: 60
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
          - refresh            

---

spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: info
    com.netflix.discovery: error
    org.nahsi.example.test.scheduler: debug

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
        exclude: "env,beans"  

---
