server: 
  port: 0 #required by spring boot to assign a random port

spring:
  cloud:
    config:
      auto-refresh: true
      refresh-interval: 60
    azure:
      keyvault:
        secret:
          property-sources:
            - endpoint: 'https://nahsi-poc-vault.vault.azure.net/'
              credential:
                managed-identity-enabled: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
          - refresh

# only req is running local
eureka:
  instance:
    preferIpAddress: true
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: info
    org.springframework.cloud.netflix: error
    com.netflix.discovery: error

# shall include: "*" in non production only
---

spring:
  config:
    activate:
      on-profile: dev
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
---        