
---

spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: info
    org.nahsi.example.test.config: debug

---
