server:
  port: 9999

testProperty: update property setting 5 Aug 14:20

spring:
  cloud:
    config:
      auto-refresh: true
      refresh-interval: 60
    azure:
      keyvault:
        secret:
          property-sources:
            - endpoint: 'https://nahsi-poc-vault.vault.azure.net/'
              credential:
                managed-identity-enabled: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
          - refresh

---

spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: debug
    org.springframework.web: debug
    org.springframework.security: info
    org.springframework.cloud.netflix: error
    com.netflix.discovery: error

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---